name: push

on:
  push:
    branches: [main]

jobs:
  build-ci:
    runs-on: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@master

    - name: Install dependencies
      working-directory: ./explory
      run:  | 
        npm install
        npm install -g @quasar/cli -f
        quasar build -m electron -f

    - name: Artifact upload
      uses: actions/upload-artifact@v2
      with:
        name: explory
        path: explory/dist/electron/explory-win32-x64/


